bsdiff "DELTARUNE/data_vanilla.win" "DELTARUNE/data.win" "exportmods/bsdiff/chapter_0.bsdiff"
bsdiff "DELTARUNE/chapter1_windows/data_vanilla.win" "DELTARUNE/chapter1_windows/data.win" "exportmods/bsdiff/chapter_1.bsdiff"
bsdiff "DELTARUNE/chapter2_windows/data_vanilla.win" "DELTARUNE/chapter2_windows/data.win" "exportmods/bsdiff/chapter_2.bsdiff"
bsdiff "DELTARUNE/chapter3_windows/data_vanilla.win" "DELTARUNE/chapter3_windows/data.win" "exportmods/bsdiff/chapter_3.bsdiff"
bsdiff "DELTARUNE/chapter4_windows/data_vanilla.win" "DELTARUNE/chapter4_windows/data.win" "exportmods/bsdiff/chapter_4.bsdiff"
bsdiff "DELTARUNE/chapter5_windows/data_vanilla.win" "DELTARUNE/chapter5_windows/data.win" "exportmods/bsdiff/chapter_5.bsdiff"