deltaruneTargetVersion = "v253"

[metadata]
name = "DELTARUNE Archipelago"
version = "2.1.0-beta4-4"
description = "Archipelago is a cross-game solo or multiplayer randomizer."
author = [ "Tenebrosful", "theemeraldsword85" ]
url = "https://discord.gg/archipelago"
tags = [ "customization", "other" ]
game = "toby.deltarune"
packageID = "gamebanana.archipelago.tenebrosful"

[color]
r = 255
g = 255
b = 255

[[neededFiles]]
file = "./data.win"
checksum = "83A5A14F9B92A20F21FB9EC6C8528469"

[[neededFiles]]
file = "./chapter1_windows/data.win"
checksum = "0CCBFD7C4F9FB1B86DE1E2AAEC0BACC9"

[[neededFiles]]
file = "./chapter2_windows/data.win"
checksum = "1592C9BFFA2D9E53DDEEDC0C4F9A07D6"

[[neededFiles]]
file = "./chapter3_windows/data.win"
checksum = "B43158DB2E958E767EBB1AAE72FB05A1"

[[neededFiles]]
file = "./chapter4_windows/data.win"
checksum = "27E36F883F4ADE21707DC8261072D416"

[[neededFiles]]
file = "./chapter5_windows/data.win"
checksum = "9C80E6300E0548D933CC006F3C22760D"

[exporter]
tool = "MiscTools"
