/// PATCH

/// REPLACE
    c_msgnextloc("* TOO BAD^1! SEE YOU KID!/%", "obj_ch2_city05_slash_Step_0_gml_638_0");
    c_talk();
    c_shakeobj();
    c_soundplay(snd_damage);
    c_var("siner_add0", 0.8);
    c_wait_box(1);
    c_shakeobj();
    c_soundplay(snd_damage);
    c_var("siner_add0", 1);
    c_wait_box(2);
    c_shakeobj();
    c_soundplay(snd_damage);
    c_var("siner_add0", 1.2);
    c_wait_box(3);
    c_shakeobj();
    c_soundplay(snd_damage);
    c_var("siner_add0", 1.5);
    c_wait_box(4);
    c_sprite(spr_cutscene_14_spamton_grab);
    c_soundplay(snd_item);
    c_var("siner_add0", 0);
    c_wait_box(5);
    c_sprite(spr_cutscene_14_spamton_hands);
    c_waittalk();
    c_halt();
    c_flip("x");
    c_walk("r", 5, 90);
    c_pannable(1);
    c_panobj(kr_actor, 30);
    c_wait(60);
    c_pannable(0);
/// CODE
    c_msgnextloc("* .../", "obj_ch2_city05_slash_Step_0_gml_638_0");
    c_msgnextloc("* AH^1, FORGET IT./", "obj_ch2_city05_slash_Step_0_gml_638_0");
    global.flag[309] = 1;
    c_talk();
    c_shakeobj();
    c_soundplay(snd_damage);
    c_var("siner_add0", 0.8);
    c_wait_box(1);
    c_shakeobj();
    c_soundplay(snd_damage);
    c_var("siner_add0", 1);
    c_wait_box(2);
    c_shakeobj();
    c_soundplay(snd_damage);
    c_var("siner_add0", 1.2);
    c_wait_box(3);
    c_shakeobj();
    c_soundplay(snd_damage);
    c_var("siner_add0", 1.5);
    c_wait_box(4);
    c_sprite(spr_cutscene_14_spamton_grab);
    c_soundplay(snd_item);
    c_var("siner_add0", 0);
    c_wait_box(5);
    c_sprite(spr_cutscene_14_spamton_hands);
    c_waittalk();
    c_speaker("spamton");
    c_msgnextloc("* LOOK, Kid./", "obj_ch2_city05_slash_Step_0_gml_553_0");
    c_msgnextloc("* YOU'RE QUITE [Big N' Strong] YOURSELF./", "obj_ch2_city05_slash_Step_0_gml_553_0");
    c_msgnextloc("* IF YOU COULD DO ME JUST A [[Eensy Weensy Favor]].../", "obj_ch2_city05_slash_Step_0_gml_553_0");
    c_msgnextloc("* YOU'LL GET MY [100`% Money Back Guarantee.]/", "obj_ch2_city05_slash_Step_0_gml_553_0");
    c_msgnextloc("* I'LL BE WAITING AT MY [[Home-made Storefront Site]]/", "obj_ch2_city05_slash_Step_0_gml_553_0");
    c_msgnextloc("* IN THE [[Trash Area Closed For Repairs.]]/%", "obj_ch2_city05_slash_Step_0_gml_554_0");
    c_talk_wait();
    c_sprite(spr_cutscene_14_spamton_dark);
    c_var("siner_add0", 0);
    c_speaker("spamton");
    c_msgsetloc(0, "* COME..^1. ALONE./%", "obj_ch2_city05_slash_Step_0_gml_564_0");
    c_talk_wait();
    c_sprite(spr_cutscene_14_spamton_laugh_left);
    c_halt();
    c_var("siner_add0", 0.1);
    c_speaker("spamton");
    c_msgsetloc(0, "* AND DON'T..^1. FORGET!/%", "obj_ch2_city05_slash_Step_0_gml_574_0");
    c_talk_wait();
    c_sprite(spr_cutscene_14_spamton);
    c_halt();
    c_speaker("spamton");
    c_msgsetloc(0, "* TO [[Like and Subscribe]] FOR MORE [[Hyperlink Blocked.]]/%", "obj_ch2_city05_slash_Step_0_gml_582_0");
    c_talk_wait();
    c_sprite(spr_cutscene_14_spamton_laugh_glitch);
    c_imagespeed(0.25);
    c_walk("r", 5, 90);
    c_speaker("spamton");
    c_msgsetloc(0, "* HAEAHAEAHAEAHAEAH!!/%", "obj_ch2_city05_slash_Step_0_gml_591_0");
    c_talk_wait();
    c_pannable(1);
    c_panobj(kr_actor, 30);
    c_wait(60);
    c_pannable(0);
/// END